### ISSUE TITLE
RuntimeError: Unexpected type () for parameter AllocateStauts. 

### ISSUE THREAD

**Issue by WilliamLINWEN** [ECPay/ECPayAIO_RoR#2]
範例`query_transac_csv(下載特店對帳媒體檔)`中，參數名稱`AllocateStauts`是否打錯？

根據你們的[文件](https://www.ecpay.com.tw/Content/files/ecpay_011.pdf)，參數名稱是`AllocateStauts`吧？

輸入參數`'AllocateStauts' => '0'`後則會報錯，錯誤訊息為`RuntimeError: Unexpected type () for parameter AllocateStauts. `

**Comment by AllennChang** [comment]
您好, 感謝你的反應, 我們已更新範例程式, 再次謝謝您
